### Storage Load
GET localhost:8084/files/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{$auth.token("Keycloak")}}

### Gateway Storage Load
GET localhost:8082/storage/files/00000000-0000-0000-0000-000000000000
Authorization: Bearer {{$auth.token("Keycloak")}}

### Notification Send
GRPC localhost:9093/com.github.gogolivan.springplatform.notification.Notification/SendNotification

### Notification Read
GRAPHQL localhost:8083/graphql
Authorization: Bearer {{$auth.token("Keycloak")}}

query {
    notification(username: "admin") {
        id,
        title,
        message,
        createdAt
    }
}