server:
  port: 8083

spring:
  grpc:
    server:
      enabled: ${GRPC_SERVER_ENABLED:true}
      port: ${GRPC_SERVER_PORT:9093}
      reflection:
        enabled: true

otel:
  exporter:
    otlp:
      traces:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
        protocol: grpc
  sdk:
    disabled: ${OTEL_SDK_DISABLED:false} # Disable OpenTelemetry
  logs:
    exporter: none
  metrics:
    exporter: none

management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.1}

logging:
  level:
    com:
      github:
        gogolivan:
          springplatform:
            notification: ${LOGGING_LEVEL_NOTIFICATION:DEBUG}