server:
  port: ${SERVER_PORT:8082}

spring:
  cloud:
    vault:
      enabled: ${SPRING_CLOUD_VAULT_ENABLED:false}
    gateway:
      server:
        webmvc:
          routes:
            - id: notification
              uri: http://localhost:8083
              predicates:
                - Path=/notification/**
              filters:
                - RewritePath=/notification/?(?<segment>.*), /$\{segment}
                - TokenRelay= # spring-boot-starter-oauth2-client required
            - id: storage
              uri: http://localhost:8083
              predicates:
                - Path=/storage/**
              filters:
                - RewritePath=/storage/?(?<segment>.*), /$\{segment}
                - TokenRelay=


otel:
  exporter:
    otlp:
      traces:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
        protocol: grpc
  sdk:
    disabled: ${OTEL_SDK_DISABLED:false} # Disable OpenTelemetry
  logs:
    exporter: none
  metrics:
    exporter: none

management:
  tracing:
    sampling:
      probability: 0.1
