server:
  port: ${SERVER_PORT:8082}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE_SERVER_ISSUER_URI:http://localhost/keycloak/realms/test}
  cloud:
    vault:
      enabled: ${SPRING_CLOUD_VAULT_ENABLED:false}
    gateway:
      server:
        webmvc:
          routes:
            - id: notification
              uri: ${SPRING_CLOUD_GATEWAY_ROUTE_NOTIFICATION:http://localhost:8083}
              predicates:
                - Path=/notification/**
              filters:
                - RewritePath=/notification/?(?<segment>.*), /$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - id: storage
              uri: ${SPRING_CLOUD_GATEWAY_ROUTE_STORAGE:http://localhost:8084}
              predicates:
                - Path=/storage/**
              filters:
                - RewritePath=/storage/?(?<segment>.*), /$\{segment}
                - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin


otel:
  exporter:
    otlp:
      traces:
        endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4317}
        protocol: grpc
  sdk:
    disabled: ${OTEL_SDK_DISABLED:false} # Disable OpenTelemetry
  logs:
    exporter: none
  metrics:
    exporter: none

management:
  tracing:
    sampling:
      probability: ${MANAGEMENT_TRACING_SAMPLING_PROBABILITY:0.1}
